[opcache]
; Enable OPcache
opcache.enable=1
opcache.enable_cli=0

; Memory settings
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000

; Performance settings
opcache.revalidate_freq=2
opcache.fast_shutdown=1

; Production settings
opcache.validate_timestamps=0
opcache.save_comments=1
opcache.enable_file_override=0
